[project]
name = "certicate-web-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "opencv-python>=4.11.0.86",
    "pillow>=11.2.1",
]
